# Generated by Django 5.2.17 on 2026-10-05 22:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("file", models.FileField(upload_to="newsletter-images/")),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("preheader", models.CharField(blank=True, max_length=200)),
                ("blocks", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CampaignRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("subject", models.CharField(max_length=200)),
                ("preheader", models.CharField(blank=True, max_length=200)),
                ("blocks", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="campaigns.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RevisionAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="campaigns.asset"
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="campaigns.campaignrevision"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="campaignrevision",
            constraint=models.UniqueConstraint(
                fields=("campaign", "number"), name="unique_revision_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="revisionasset",
            constraint=models.UniqueConstraint(
                fields=("revision", "asset"), name="unique_revision_asset"
            ),
        ),
    ]
