# Generated by Django 5.2.17 on 2026-10-09 16:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="contact",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name="MailchimpRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("batch_id", models.UUIDField(db_index=True)),
                ("source_status", models.CharField(default="subscribed", max_length=20)),
                ("marketing_flag", models.BooleanField(null=True)),
                ("leid", models.CharField(blank=True, max_length=80)),
                ("euid", models.CharField(blank=True, max_length=80)),
                ("source", models.CharField(blank=True, max_length=254)),
                ("source_data", models.JSONField(default=dict)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="contacts.contact"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch_id", "contact"), name="unique_import_contact"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source_status", "subscribed")),
                        name="active_mailchimp_source_only",
                    ),
                ],
            },
        ),
    ]
