# Generated by Django 5.2.17 on 2026-10-09 18:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_contact_first_name_contact_last_name_mailchimprecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("filename", models.CharField(max_length=254)),
                ("file_sha256", models.CharField(max_length=64)),
                ("delimiter", models.CharField(max_length=1)),
                ("ignored_columns", models.JSONField(default=list)),
                ("rows", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preview", "Vorschau"),
                            ("completed", "Übernommen"),
                            ("cancelled", "Verworfen"),
                        ],
                        default="preview",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["preview", "completed", "cancelled"])),
                        name="valid_import_batch_status",
                    )
                ],
            },
        ),
    ]
