# Generated by Django 5.2.17 on 2026-10-05 22:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfirmationToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConsentEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("requested", "Angefordert"),
                            ("confirmed", "Bestätigt"),
                            ("withdrawn", "Widerrufen"),
                        ],
                        max_length=20,
                    ),
                ),
                ("purpose", models.CharField(default="newsletter", max_length=20)),
                ("text_version", models.CharField(max_length=80)),
                ("text", models.TextField()),
                ("source", models.CharField(max_length=40)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RateLimitBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConfirmationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("sending", "Versand begonnen"),
                            ("accepted", "Vom Adapter angenommen"),
                            ("failed", "Fehlgeschlagen"),
                            ("uncertain", "Ausgang unklar"),
                            ("cancelled", "Nicht mehr benötigt"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="consents.confirmationtoken"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="confirmationtoken",
            name="evidence",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="consents.consentevidence"
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Bestätigung ausstehend"),
                            ("active", "Aktiv"),
                            ("unsubscribed", "Abgemeldet"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("tracking_allowed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="contacts.contact"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consentevidence",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="consents.subscription"
            ),
        ),
        migrations.CreateModel(
            name="ConsentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("cause_id", models.UUIDField()),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="consents.subscription"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="confirmationtoken",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="consents.subscription"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "active", "unsubscribed"])),
                name="valid_subscription_status",
            ),
        ),
    ]
