# Generated by Django 5.2.17 on 2026-10-09 16:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


def assign_message_ids(apps, schema_editor):
    Message = apps.get_model("consents", "ConfirmationMessage")
    database = schema_editor.connection.alias
    for pk in Message.objects.using(database).values_list("pk", flat=True).iterator():
        Message.objects.using(database).filter(pk=pk).update(message_id=uuid.uuid4())


class Migration(migrations.Migration):
    dependencies = [
        ("consents", "0001_initial"),
        ("contacts", "0002_contact_first_name_contact_last_name_mailchimprecord"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscription",
            name="valid_subscription_status",
        ),
        migrations.AddField(
            model_name="confirmationmessage",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="confirmationmessage",
            name="attempted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="confirmationmessage",
            name="body_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="confirmationmessage",
            name="body_snapshot",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="confirmationmessage",
            name="message_id",
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(assign_message_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="confirmationmessage",
            name="message_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="confirmationmessage",
            name="recipient",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="confirmationmessage",
            name="sender",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="confirmationmessage",
            name="subject",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="consentevidence",
            name="confirmation_reference",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consentevidence",
            name="email_snapshot",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="consentevidence",
            name="privacy_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="consentevidence",
            name="privacy_version",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="consentevidence",
            name="remote_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consentevidence",
            name="request_evidence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="followup_evidence",
                to="consents.consentevidence",
            ),
        ),
        migrations.AddField(
            model_name="consentevidence",
            name="text_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("imported", "Importiert – neue Bestätigung erforderlich"),
                    ("pending", "Bestätigung ausstehend"),
                    ("active", "Aktiv"),
                    ("unsubscribed", "Abgemeldet"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["imported", "pending", "active", "unsubscribed"])
                ),
                name="valid_subscription_status",
            ),
        ),
    ]
